# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('name', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='static/images')),
            ],
        ),
    ]
